version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./db_data/db:/var/lib/mysql
    env_file:
      - ./.env
      
  wordpress:
    build:
      context: ./wordpress
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8001:80"
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    volumes:
      - ./wordpress_data/uploads:/var/www/html/wp-content/uploads
    env_file:
      - ./.env

  phpmyadmin:
    build:
      context: ./phpmyadmin
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: ${PMA_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASSWORD}
    env_file:
      - ./.env
