version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mdp
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - ./db_data/db:/var/lib/mysql
      
  wordpress:
    build:
      context: ./wordpress
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8001:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress_data/uploads:/var/www/html/wp-content/uploads

  phpmyadmin:
    build:
      context: ./phpmyadmin
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: mdp
      PMA_USER: root
      PMA_PASSWORD: mdp
