version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - ./sql_db/db:/var/lib/mysql  
    restart: always
    networks:
      - wp-network
    env_file:
      - ./database/.env

  wordpress:
    build:
      context: ./wordpress
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - ./wordpress_db/uploads:/var/www/html/wp-content/uploads  
    ports:
      - "8000:80"
    restart: always
    networks:
      - wp-network
    env_file:
      - ./wordpress/.env
    

  phpmyadmin:
    build:
      context: ./phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    restart: always
    networks:
      - wp-network
    env_file:
      - ./phpmyadmin/.env

networks:
  wp-network: