version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - ./sql_data/db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dbpass
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    
  wordpress:
    depends_on:
      - db
    build:
      context: ./wordpress
      dockerfile: Dockerfile
    ports:
      - "8001:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wdp_file/uploads:/var/www/html/wp-content/uploads

  phpmyadmin:
    depends_on:
      - db
    build:
      context: ./phpmyadmin
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: dbpass
